eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${eureka.instance.instance_id:${random.int[1,9999]}}
server:
  port: ${PORT:0}
spring:
  application:
    name: users-ws
  devtools:
    restart:
      enabled: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
