#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    reactor.netty.http.client: DEBUG
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8082
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: users-status-check
          uri: lb://users-ws
          predicates:
          - Path=/users/info
          
#        - id: h2
#          uri: lb:/users-ws
#          predicates:
#          - Path=/h2-console
#          filters:
#          - RewritePath=/users-ws(?<segment>/?.*), $\{segment}
            
       
